### ISSUE TITLE
JS style comments support is missing

### ISSUE THREAD

**Issue by mvasin** [styled-components/stylelint-processor-styled-components#195] opened 2018-05-30 15:45 UTC
`styled-components` support JS-style comments `//`, but the linter is unaware of that; I get
```
 111:3   ✖  Unexpected unknown        property-no-unknown
            property "//"
```

**Comment by chinesedfan** [comment] 2018-05-31 03:08
@mvasin Please provide code snippets and your packages version. According to #156, it should work.

**Comment by mvasin** [comment] 2018-05-31 07:11
Sure! The '//' problem is at line 110. You can also notice problem at line 91, but I guess that's another issue.

<img width="835" alt="screen shot 2018-05-31 at 10 08 39" src="https://user-images.githubusercontent.com/12434833/40767247-a282f55e-64ba-11e8-877c-41c8fda8b2f0.png">

Here are the packages I use:
```
$ cat package.json | grep stylelint
    "lint:css": "stylelint './src/**/*.js'"
    "stylelint": "^9.2.1",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.3.1"

$ cat package-lock.json | grep stylelint
    "stylelint": {
      "resolved": "https://registry.npmjs.org/stylelint/-/stylelint-9.2.1.tgz",
    "stylelint-config-recommended": {
      "resolved": "https://registry.npmjs.org/stylelint-config-recommended/-/stylelint-config-recommended-2.1.0.tgz",
    "stylelint-config-standard": {
      "resolved": "https://registry.npmjs.org/stylelint-config-standard/-/stylelint-config-standard-18.2.0.tgz",
        "stylelint-config-recommended": "^2.1.0"
    "stylelint-config-styled-components": {
      "resolved": "https://registry.npmjs.org/stylelint-config-styled-components/-/stylelint-config-styled-components-0.1.1.tgz",
    "stylelint-processor-styled-components": {
      "resolved": "https://registry.npmjs.org/stylelint-processor-styled-components/-/stylelint-processor-styled-components-1.3.1.tgz",
```

**Comment by chinesedfan** [comment] 2018-05-31 07:56
Try to run with `"lint:css": "stylelint './src/**/*.js'  --syntax scss"`

**Comment by Undistraction** [comment] 2018-05-31 08:37
Same problem here. 

Simple Example:

```
const Layout = styled.div`
 // Comment
`
```

The first `/` is flagged with:

> [style-lint] Unknown word (Css Syntax Error)

**Comment by Undistraction** [comment] 2018-05-31 08:45
@chinesedfan If I run it with `--syntax css` the error is not flagged, however other errors (that aren't present when running it without *are* flagged.

**Comment by chinesedfan** [comment] 2018-05-31 08:48
@Undistraction `--syntax scss`, instead of `--syntax css`. If you are still confused with new errors, please reopen #199 and provide your detail environments information like above.

**Comment by Undistraction** [comment] 2018-05-31 09:02
@chinesedfan Are you saying users of this plugin must use `--syntax scss` for it to function correctly?

**Comment by chinesedfan** [comment] 2018-05-31 09:38
@Undistraction According to https://github.com/styled-components/stylelint-processor-styled-components/issues/156#issuecomment-367418339, I am afraid it is.

> however other errors (that aren't present when running it without) are flagged.

Can you paste `other errors`? BTW, we have updated `stylelint-config-standard` to `stylelint-config-recommended` in the README.

**Comment by Undistraction** [comment] 2018-05-31 10:39
> BTW, we have updated stylelint-config-standard to stylelint-config-recommended in the README.

@chantastic Thanks very much. I think some of issues lay there.

> @Undistraction According to #156 (comment), I am afraid it is.

So shouldn't the config in the README include this?

```
{
  "processors": ["stylelint-processor-styled-components"],
  "syntax": "scss",
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ]
}
```

**Comment by chinesedfan** [comment] 2018-05-31 11:05
> So shouldn't the config in the README include this?

@Undistraction Right. I will confirm with @emilgoldsmith in #156. (And you pinged `chantastic` by mistake. 😆)

**Comment by Undistraction** [comment] 2018-05-31 11:17
Sorry chantastic (I won't ping you again to apologise). 

FWIW I'm still seeing the comments being flagged with the following config:

```
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ],
  "syntax": "scss",
  "rules": {
    "block-no-empty": null
  }
}
```

**Comment by mvasin** [comment] 2018-05-31 11:31
With the config above, most other errors went away, but the original `//` error (and one more) persist. Is it some overlooked edge case? Here's the screenshot.
<img width="1269" alt="screen shot 2018-05-31 at 14 28 47" src="https://user-images.githubusercontent.com/12434833/40779861-2d4b154e-64df-11e8-8f88-0350ce6f72f2.png">

**Comment by mvasin** [comment] 2018-05-31 11:54
It still gives false positives even in the simplest case:
```
const Test1 = styled.div`
  // test
  background: red;
`
```

=>
```
 99:3  ✖  Unexpected double-slash CSS comment   no-invalid-double-slash-comments
 99:3  ✖  Unexpected unknown property "//"      property-no-unknown
```

**Comment by chinesedfan** [comment] 2018-05-31 13:54
@mvasin Can you try with `--syntax scss`?

@Undistraction According to #170, the `syntax` field in the config file does not work. You have to add it in the CLI options. If confirmed, I will try to update our documents.

**Comment by Undistraction** [comment] 2018-05-31 14:17
@chinesedfan I couldn't see any mention of needing to use the CLI opts in the linked issue and unfortunately I'm using VSCode with an extension to run stylelint which doesn't allow you to pass in opts.

Anyway, this needs to be added to README as this is far from obvious, and I'm assuming most people will experience this as soon as they use JS-style comments.

**Comment by mvasin** [comment] 2018-05-31 15:12
@chinesedfan Indeed, `"lint:css": "stylelint './src/**/*.js' --syntax scss"` in package.json indeed solves the `//` problem.

It's all very confusing, I thought `"syntax": "scss"` and `--syntax scss` have equal effect. Even more confusing is [this issue](https://github.com/styled-components/stylelint-processor-styled-components/issues/170) about removing `"syntax": "scss"`.

Why do we have to specify this option, can't it be a default, if (at least) `//` comments are part of styled-components anyway?

**Comment by chinesedfan** [comment] 2018-05-31 15:48
@Undistraction Sorry for that I can't give you more suggestions. Maybe you really have to open an issue in [styled-components/vscode-styled-components](https://github.com/styled-components/vscode-styled-components) and I am glad to be @ and receive progresses.

> It's all very confusing, I thought "syntax": "scss" and --syntax scss have equal effect.

@mvasin You can read more in https://github.com/stylelint/stylelint/issues/2973.

> Why do we have to specify this option, can't it be a default, if (at least) // comments are part of styled-components anyway?

It is due to js-style comments are not valid in `css`, but valid in `scss`.

---

Thanks you two guys! I will close this issue with some updates in README to reflect our discussions.

**Closed by chinesedfan** 2018-05-31 15:48 UTC

**Comment by Undistraction** [comment] 2018-05-31 15:51
@chinesedfan Thanks for your help. I'll open an issue and link you in. It's a shame this can't be part of the processor so it is configured automatically.

**Comment by emilgoldsmith** [comment] 2018-05-31 17:28
Hey guys, if any of you have the time, I'd be curious if you could write a unit test that fails? Because our tests that were introduced in #164 all pass. Is it because you're using an old node version or something weird?

And we don't use any of those options you guys talk about (and also what is explained in #170 @mvasin was that apparently we had been using that config option but it actually doesn't do anything at all, it's actually not a Stylelint option)

**Comment by mvasin** [comment] 2018-05-31 18:06
@emilgoldsmith I ran the `stylelint-processor-styled-components` test suite and it passes. I'll try to contribute a failing test.

**Comment by mvasin** [comment] 2018-05-31 18:46
Here are my current steps to reproduce a failing test:

1. Clone the `stylelint-processor-styled-components` repo
2. Rename `stylelint-processor-styled-components` in `package.json` to anything else to be able to install `stylelint-processor-styled-components` from npm on the next step.
3. `npm install stylelint-processor-styled-components stylelint-config-recommended stylelint-config-styled-components`
4. Install the rest: `npm install`
5. Save this
```
{
  "processors": ["stylelint-processor-styled-components"],
  "syntax": "scss",
  "extends": [
    "stylelint-config-recommended",
    "stylelint-config-styled-components"
  ]
}
```
to `.stylelintrc` in the root of the project
5. Run `node_modules/.bin/stylelint test/fixtures/hard/valid-js-comments.js`

And there you have it:
```
test/fixtures/hard/valid-js-comments.js
 6:3   ✖  Unexpected double-slash CSS comment   no-invalid-double-slash-comments
 6:3   ✖  Unexpected unknown property "//"      property-no-unknown
 7:32  ✖  Unexpected double-slash CSS comment   no-invalid-double-slash-comments
 7:32  ✖  Unexpected unknown property "//"      property-no-unknown
```

I guess the one who wrote the test will figure out faster why the tests pass while they shouldn't.

Another cautious observation: when I try to see the test failing replacing
```
  // Some comment
```
with
```
  / Some comment
```
in `test/fixtures/hard/valid-js-comments.js`, the test suite still passes! That's a bad sign.

I'm afraid that's all I can help with for now.

**Comment by mvasin** [comment] 2018-05-31 18:50
I think the test suite should resemble readme recommendations as close as possible - include and use `.stylelintrc` as readme suggests.

**Comment by emilgoldsmith** [comment] 2018-05-31 19:50
That's very helpful @mvasin, thanks! I'm afraid I don't have the time to look further into this at the moment, but this is definitely very helpful and is something that should be investigated further by someone who has the time!

**Comment by Undistraction** [comment] 2018-06-02 07:34
FWIW the owner of the style-lint VSCode plugin will not add the ability to pass command line args through to stylelint: https://github.com/shinnn/vscode-stylelint/issues/209#issuecomment-394055506 The only other solution (other than enabling this via this plugin) is to try and get styelint to add the `syntax` key in `.stylelintrc`, but the issue [here](https://github.com/stylelint/stylelint/issues/2973) means I think they are unlikely to do this.

**Comment by chinesedfan** [comment] 2018-06-02 09:42
> but the issue here means I think they are unlikely to do this

@Undistraction I remind you to clarify differences between https://github.com/stylelint/stylelint/issues/2973 use cases and yours. Because that issue is requesting supports in `.vue` files, which can be resolved by `<style lang="scss">`. But you have nothing to indicate the syntax.

Good luck and I am still glad to be @ with. 😄
