### ISSUE TITLE
Update package.json github references

### ISSUE THREAD

**Issue by mike3run** [styled-components/stylelint-processor-styled-components#92] opened 2017-08-15 00:16 UTC
Specially the bugs and homepage since they point to a 404 right now

https://github.com/styled-components/stylelint-processor-styled-components/blob/master/package.json#L29-L31

**Comment by emilgoldsmith** [comment] 2017-08-15 08:55
Oh yeah haha. We just fixed up #85 but didn't see it was also those 2 places. Cheers!

**Comment by ismay** [comment] 2017-08-15 09:06
Duplicate of #48

**Closed** 2017-08-15 09:15 UTC
Labels: enhancement, help welcome

**Comment by emilgoldsmith** [comment] 2017-08-15 09:32
> Duplicate of #48
Oh yeah you're right, you already had this pointed out. In that case I'll close #48 :).

**Comment by ismay** [comment] 2017-08-15 09:40
Yeah the issue was a bit vaguely worded. I should've just taken care of it immediately, thanks for handling it!
